language: csharp
solution: UnityServerBasics.sln
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "R23slK+ZhIluCUyDvrwP/+pdvq3W0OYesGuELjmUnoAJDVBFehs07BWdnE+hZSIP0nMZZD6oiKcIoyMn7khIordUtmfyM/0f2At+SghLwbw5E2m+vpa/haoom+jaO0QaapbHQcFuvckvwVz6t0puaHDPkBWDqVkUHFruIyjCcTD+2F0VzCqdyHUfVa7s9oGEbv+eRBV18dnMBy9KTGYpaXkJvNQ7yJE8ysY/FEUnWfhViE4rTuZM2UClCIZjDViOOremiemJxPsCl1KIaHBYiXn/zjZaSrVzmL81nPtzgdJOC87GoODauKpCYs7TfF+Bg9Pe2ONHfh8TFv05JzRQao3Gsz77nqnSa/VWhtmgalKflWaLT4mnHde2WOxHPvsK5I8jKAuOGUr4DDstP7VpKdy22W5bvlJkj/VmKnh6COBfD6DH5sWPnIunaf6Q2CezHmFkWxnFw91Z2lbLQ7WDbcZcwTn8yls9R3SeHbXp6790b/SezWTqQWijZ7O0hURppdRoBP8nHe659tngDmS8S9KwIOHkt2O0RBQGqmVXgwTF37+4/bkSbiObnGLnLCqteotUHzm21epiJ1X393sLYNnI7hn8XbTPBm/GEU/VVpRC7oSZ67TNtPNC1SL0L6eJpZ8s+E4L7PmiQUxAkWBC69PHqB6+w2dynqGSMOKXsAQ="

addons:
  coverity_scan:
    project:
      name: "HeadhunterXamd/BasicUDPServer"
      description: "Basic UDP game server"
    notification_email: nielsvanschooten@gmail.com
    build_command_prepend: " "
    build_command:   " "
    branch_pattern: coverity_scan
