version: 1.0.0.{build}
skip_tags: true

before_build:
  - nuget restore
build:
  verbosity: minimal
deploy:
- provider: GitHub
  tag: Server-v$(appveyor_build_version)
  release: Server-v$(appveyor_build_version)
  auth_token:
    secure: Uw4wzXu2hXQjYEnlOH1P6v6mofwXHHkGqURQawoJpvMYvEMcCoitvOIye8pg7UP7
  artifact: BasicUDPServer
  prerelease: true
  on:
    branch: deploy
