version: 1.0.0.{build}
skip_tags: true
build:
  verbosity: minimal
artifacts:
  - path: UnityServerBasics\bin\Debug\app.publish\*
    name: BasicServer
deploy:
- provider: GitHub
  tag: Server-v$(appveyor_build_version)
  release: Server-v$(appveyor_build_version)
  auth_token:
    secure: jeZGvFiamRNtZnBpNaye4YMJhg8X/QRkzEuKNq2S7oGwQAc3Ss+nqgKqtw5wz8VJ
  artifact: BasicServer
  prerelease: true
  on:
    branch: deploy
